INSERT INTO tb_banks(name, key_pix) VALUES ('Itau', 'wi4qgb0g4qgq950gqrbneqbbf');

INSERT INTO tb_products(name) VALUES ('Palha Italiana');

INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (5, 10.50, '2024-03-01', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (2, 10.50, '2024-03-02', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (3, 8.90, '2024-03-03', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (7, 12.30, '2024-03-04', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (4, 8.90, '2024-03-05', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (6, 14.25, '2024-03-06', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (1, 20.00, '2024-03-07', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (10, 10.50, '2024-03-08', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (8, 12.30, '2024-03-09', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (3, 8.90, '2024-03-10', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (5, 14.25, '2024-03-11', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (9, 12.30, '2024-03-12', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (4, 6.75, '2024-03-13', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (7, 10.50, '2024-03-14', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (2, 18.90, '2024-03-15', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (6, 10.50, '2024-03-16', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (5, 14.25, '2024-03-17', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (3, 9.25, '2024-03-18', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (8, 7.50, '2024-03-19', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (2, 16.40, '2024-03-20', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (6, 12.30, '2024-03-21', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (5, 10.50, '2024-03-22', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (9, 10.50, '2024-03-23', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (4, 7.25, '2024-03-24', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (7, 13.90, '2024-03-25', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (3, 6.80, '2024-03-26', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (5, 10.50, '2024-03-27', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (8, 12.30, '2024-03-28', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (2, 15.10, '2024-03-29', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (6, 10.50, '2024-03-30', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (5, 13.25, '2024-03-31', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (3, 8.75, '2024-04-01', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (7, 7.90, '2024-04-02', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (2, 14.60, '2024-04-03', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (6, 11.10, '2024-04-04', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (5, 10.50, '2024-04-05', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (9, 12.30, '2024-04-06', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (4, 7.10, '2024-04-07', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (7, 13.40, '2024-04-08', 1);
INSERT INTO tb_sales (amount, unit_value, date_sale, bank_id) VALUES (7, 13.40, '2024-04-08', 1);

INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 1);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 2);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 3);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 4);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 5)
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 6);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 7);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 8);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 9);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 10);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 11);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 12);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 13);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 14);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 15);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 16);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 17);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 18);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 19);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 20);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 21);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 22);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 23);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 24);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 25);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 26);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 27);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 28);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 29);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 30);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 31);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 32);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 33);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 34);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 35);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 36);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 37);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 38);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 39);
INSERT INTO tb_products_sales (product_id, sale_id) VALUES (1, 40);